// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: arceus/api/arceus_config.proto

package arceus

import (
	api "arceus/pkg/carbon/api"
	api2 "arceus/pkg/database/api"
	api1 "arceus/pkg/logger/api"
	api3 "arceus/pkg/redis/api"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listener      *api.Listener          `protobuf:"bytes,1,opt,name=listener,proto3" json:"listener,omitempty"`
	Logger        *api1.Logger           `protobuf:"bytes,2,opt,name=logger,proto3" json:"logger,omitempty"`
	Database      *api2.Database         `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *api3.Redis            `protobuf:"bytes,4,opt,name=redis,proto3" json:"redis,omitempty"`
	HttpListener  *api.Listener          `protobuf:"bytes,8,opt,name=http_listener,json=httpListener,proto3" json:"http_listener,omitempty"`
	Mistral       *AiProvider            `protobuf:"bytes,5,opt,name=mistral,proto3" json:"mistral,omitempty"`
	Openai        *AiProvider            `protobuf:"bytes,6,opt,name=openai,proto3" json:"openai,omitempty"`
	Gemini        *AiProvider            `protobuf:"bytes,7,opt,name=gemini,proto3" json:"gemini,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_arceus_api_arceus_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_arceus_api_arceus_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_arceus_api_arceus_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetListener() *api.Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

func (x *Config) GetLogger() *api1.Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *Config) GetDatabase() *api2.Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Config) GetRedis() *api3.Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Config) GetHttpListener() *api.Listener {
	if x != nil {
		return x.HttpListener
	}
	return nil
}

func (x *Config) GetMistral() *AiProvider {
	if x != nil {
		return x.Mistral
	}
	return nil
}

func (x *Config) GetOpenai() *AiProvider {
	if x != nil {
		return x.Openai
	}
	return nil
}

func (x *Config) GetGemini() *AiProvider {
	if x != nil {
		return x.Gemini
	}
	return nil
}

type AiProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Models        []string               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Enable        bool                   `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiProvider) Reset() {
	*x = AiProvider{}
	mi := &file_arceus_api_arceus_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiProvider) ProtoMessage() {}

func (x *AiProvider) ProtoReflect() protoreflect.Message {
	mi := &file_arceus_api_arceus_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiProvider.ProtoReflect.Descriptor instead.
func (*AiProvider) Descriptor() ([]byte, []int) {
	return file_arceus_api_arceus_config_proto_rawDescGZIP(), []int{1}
}

func (x *AiProvider) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AiProvider) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *AiProvider) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AiProvider) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AiProvider) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

var File_arceus_api_arceus_config_proto protoreflect.FileDescriptor

const file_arceus_api_arceus_config_proto_rawDesc = "" +
	"\n" +
	"\x1earceus/api/arceus_config.proto\x12\rarceus.config\x1a\x17validate/validate.proto\x1a\x17logger/api/logger.proto\x1a\x17carbon/api/carbon.proto\x1a\x15redis/api/redis.proto\x1a\x1bdatabase/api/database.proto\"\xe3\x03\n" +
	"\x06Config\x12?\n" +
	"\blistener\x18\x01 \x01(\v2\x19.greyhole.carbon.ListenerB\b\xfaB\x05\x8a\x01\x02\x10\x01R\blistener\x129\n" +
	"\x06logger\x18\x02 \x01(\v2\x17.greyhole.logger.LoggerB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06logger\x12A\n" +
	"\bdatabase\x18\x03 \x01(\v2\x1b.greyhole.database.DatabaseB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bdatabase\x125\n" +
	"\x05redis\x18\x04 \x01(\v2\x15.greyhole.redis.RedisB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05redis\x12H\n" +
	"\rhttp_listener\x18\b \x01(\v2\x19.greyhole.carbon.ListenerB\b\xfaB\x05\x8a\x01\x02\x10\x01R\fhttpListener\x123\n" +
	"\amistral\x18\x05 \x01(\v2\x19.arceus.config.AiProviderR\amistral\x121\n" +
	"\x06openai\x18\x06 \x01(\v2\x19.arceus.config.AiProviderR\x06openai\x121\n" +
	"\x06gemini\x18\a \x01(\v2\x19.arceus.config.AiProviderR\x06gemini\"\x83\x01\n" +
	"\n" +
	"AiProvider\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x16\n" +
	"\x06enable\x18\x05 \x01(\bR\x06enableB\x1aZ\x18arceus/pkg/config;arceusb\x06proto3"

var (
	file_arceus_api_arceus_config_proto_rawDescOnce sync.Once
	file_arceus_api_arceus_config_proto_rawDescData []byte
)

func file_arceus_api_arceus_config_proto_rawDescGZIP() []byte {
	file_arceus_api_arceus_config_proto_rawDescOnce.Do(func() {
		file_arceus_api_arceus_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arceus_api_arceus_config_proto_rawDesc), len(file_arceus_api_arceus_config_proto_rawDesc)))
	})
	return file_arceus_api_arceus_config_proto_rawDescData
}

var file_arceus_api_arceus_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_arceus_api_arceus_config_proto_goTypes = []any{
	(*Config)(nil),        // 0: arceus.config.Config
	(*AiProvider)(nil),    // 1: arceus.config.AiProvider
	(*api.Listener)(nil),  // 2: greyhole.carbon.Listener
	(*api1.Logger)(nil),   // 3: greyhole.logger.Logger
	(*api2.Database)(nil), // 4: greyhole.database.Database
	(*api3.Redis)(nil),    // 5: greyhole.redis.Redis
}
var file_arceus_api_arceus_config_proto_depIdxs = []int32{
	2, // 0: arceus.config.Config.listener:type_name -> greyhole.carbon.Listener
	3, // 1: arceus.config.Config.logger:type_name -> greyhole.logger.Logger
	4, // 2: arceus.config.Config.database:type_name -> greyhole.database.Database
	5, // 3: arceus.config.Config.redis:type_name -> greyhole.redis.Redis
	2, // 4: arceus.config.Config.http_listener:type_name -> greyhole.carbon.Listener
	1, // 5: arceus.config.Config.mistral:type_name -> arceus.config.AiProvider
	1, // 6: arceus.config.Config.openai:type_name -> arceus.config.AiProvider
	1, // 7: arceus.config.Config.gemini:type_name -> arceus.config.AiProvider
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_arceus_api_arceus_config_proto_init() }
func file_arceus_api_arceus_config_proto_init() {
	if File_arceus_api_arceus_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arceus_api_arceus_config_proto_rawDesc), len(file_arceus_api_arceus_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arceus_api_arceus_config_proto_goTypes,
		DependencyIndexes: file_arceus_api_arceus_config_proto_depIdxs,
		MessageInfos:      file_arceus_api_arceus_config_proto_msgTypes,
	}.Build()
	File_arceus_api_arceus_config_proto = out.File
	file_arceus_api_arceus_config_proto_goTypes = nil
	file_arceus_api_arceus_config_proto_depIdxs = nil
}
