// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: arceus/api/arceus.proto

package arceus

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortType int32

const (
	SortType_SORT_TYPE_UNKNOWN SortType = 0
	SortType_SORT_TYPE_ASC     SortType = 1
	SortType_SORT_TYPE_DESC    SortType = 2
)

// Enum value maps for SortType.
var (
	SortType_name = map[int32]string{
		0: "SORT_TYPE_UNKNOWN",
		1: "SORT_TYPE_ASC",
		2: "SORT_TYPE_DESC",
	}
	SortType_value = map[string]int32{
		"SORT_TYPE_UNKNOWN": 0,
		"SORT_TYPE_ASC":     1,
		"SORT_TYPE_DESC":    2,
	}
)

func (x SortType) Enum() *SortType {
	p := new(SortType)
	*p = x
	return p
}

func (x SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_arceus_api_arceus_proto_enumTypes[0].Descriptor()
}

func (SortType) Type() protoreflect.EnumType {
	return &file_arceus_api_arceus_proto_enumTypes[0]
}

func (x SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortType.Descriptor instead.
func (SortType) EnumDescriptor() ([]byte, []int) {
	return file_arceus_api_arceus_proto_rawDescGZIP(), []int{0}
}

type Role int32

const (
	Role_ROLE_UNKNOWN Role = 0
	Role_ROLE_BOT     Role = 1
	Role_ROLE_USER    Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "ROLE_BOT",
		2: "ROLE_USER",
	}
	Role_value = map[string]int32{
		"ROLE_UNKNOWN": 0,
		"ROLE_BOT":     1,
		"ROLE_USER":    2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_arceus_api_arceus_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_arceus_api_arceus_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_arceus_api_arceus_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=arceus.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_arceus_api_arceus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_arceus_api_arceus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_arceus_api_arceus_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_arceus_api_arceus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_arceus_api_arceus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_arceus_api_arceus_proto_rawDescGZIP(), []int{1}
}

func (x *Conversation) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Conversation) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SortMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          SortType               `protobuf:"varint,2,opt,name=type,proto3,enum=arceus.SortType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortMethod) Reset() {
	*x = SortMethod{}
	mi := &file_arceus_api_arceus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortMethod) ProtoMessage() {}

func (x *SortMethod) ProtoReflect() protoreflect.Message {
	mi := &file_arceus_api_arceus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortMethod.ProtoReflect.Descriptor instead.
func (*SortMethod) Descriptor() ([]byte, []int) {
	return file_arceus_api_arceus_proto_rawDescGZIP(), []int{2}
}

func (x *SortMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SortMethod) GetType() SortType {
	if x != nil {
		return x.Type
	}
	return SortType_SORT_TYPE_UNKNOWN
}

type GenerateTextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Model          string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ConversationId *uint64                `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateTextRequest) Reset() {
	*x = GenerateTextRequest{}
	mi := &file_arceus_api_arceus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextRequest) ProtoMessage() {}

func (x *GenerateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arceus_api_arceus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextRequest.ProtoReflect.Descriptor instead.
func (*GenerateTextRequest) Descriptor() ([]byte, []int) {
	return file_arceus_api_arceus_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateTextRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateTextRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateTextRequest) GetConversationId() uint64 {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return 0
}

type GenerateTextResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ConversationId uint64                 `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Usage          *Usage                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateTextResponse) Reset() {
	*x = GenerateTextResponse{}
	mi := &file_arceus_api_arceus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextResponse) ProtoMessage() {}

func (x *GenerateTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arceus_api_arceus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextResponse.ProtoReflect.Descriptor instead.
func (*GenerateTextResponse) Descriptor() ([]byte, []int) {
	return file_arceus_api_arceus_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateTextResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateTextResponse) GetConversationId() uint64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GenerateTextResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GenerateTextResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,3,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_arceus_api_arceus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_arceus_api_arceus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_arceus_api_arceus_proto_rawDescGZIP(), []int{5}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

var File_arceus_api_arceus_proto protoreflect.FileDescriptor

const file_arceus_api_arceus_proto_rawDesc = "" +
	"\n" +
	"\x17arceus/api/arceus.proto\x12\x06arceus\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\aMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12 \n" +
	"\x04role\x18\x02 \x01(\x0e2\f.arceus.RoleR\x04role\"K\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12+\n" +
	"\bmessages\x18\x02 \x03(\v2\x0f.arceus.MessageR\bmessages\"O\n" +
	"\n" +
	"SortMethod\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.arceus.SortTypeR\x04type\"\x87\x01\n" +
	"\x13GenerateTextRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12,\n" +
	"\x0fconversation_id\x18\x03 \x01(\x04H\x00R\x0econversationId\x88\x01\x01B\x12\n" +
	"\x10_conversation_id\"\xb9\x01\n" +
	"\x14GenerateTextResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x04R\x0econversationId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\x05usage\x18\x04 \x01(\v2\r.arceus.UsageR\x05usage\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x05R\vtotalTokens\x12+\n" +
	"\x11completion_tokens\x18\x03 \x01(\x05R\x10completionTokens*H\n" +
	"\bSortType\x12\x15\n" +
	"\x11SORT_TYPE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSORT_TYPE_ASC\x10\x01\x12\x12\n" +
	"\x0eSORT_TYPE_DESC\x10\x02*5\n" +
	"\x04Role\x12\x10\n" +
	"\fROLE_UNKNOWN\x10\x00\x12\f\n" +
	"\bROLE_BOT\x10\x01\x12\r\n" +
	"\tROLE_USER\x10\x022u\n" +
	"\x06Arceus\x12k\n" +
	"\fGenerateText\x12\x1b.arceus.GenerateTextRequest\x1a\x1c.arceus.GenerateTextResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/chat/completionsB\x13Z\x11arceus/api;arceusb\x06proto3"

var (
	file_arceus_api_arceus_proto_rawDescOnce sync.Once
	file_arceus_api_arceus_proto_rawDescData []byte
)

func file_arceus_api_arceus_proto_rawDescGZIP() []byte {
	file_arceus_api_arceus_proto_rawDescOnce.Do(func() {
		file_arceus_api_arceus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arceus_api_arceus_proto_rawDesc), len(file_arceus_api_arceus_proto_rawDesc)))
	})
	return file_arceus_api_arceus_proto_rawDescData
}

var file_arceus_api_arceus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_arceus_api_arceus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_arceus_api_arceus_proto_goTypes = []any{
	(SortType)(0),                 // 0: arceus.SortType
	(Role)(0),                     // 1: arceus.Role
	(*Message)(nil),               // 2: arceus.Message
	(*Conversation)(nil),          // 3: arceus.Conversation
	(*SortMethod)(nil),            // 4: arceus.SortMethod
	(*GenerateTextRequest)(nil),   // 5: arceus.GenerateTextRequest
	(*GenerateTextResponse)(nil),  // 6: arceus.GenerateTextResponse
	(*Usage)(nil),                 // 7: arceus.Usage
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_arceus_api_arceus_proto_depIdxs = []int32{
	1, // 0: arceus.Message.role:type_name -> arceus.Role
	2, // 1: arceus.Conversation.messages:type_name -> arceus.Message
	0, // 2: arceus.SortMethod.type:type_name -> arceus.SortType
	8, // 3: arceus.GenerateTextResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 4: arceus.GenerateTextResponse.usage:type_name -> arceus.Usage
	5, // 5: arceus.Arceus.GenerateText:input_type -> arceus.GenerateTextRequest
	6, // 6: arceus.Arceus.GenerateText:output_type -> arceus.GenerateTextResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_arceus_api_arceus_proto_init() }
func file_arceus_api_arceus_proto_init() {
	if File_arceus_api_arceus_proto != nil {
		return
	}
	file_arceus_api_arceus_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arceus_api_arceus_proto_rawDesc), len(file_arceus_api_arceus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arceus_api_arceus_proto_goTypes,
		DependencyIndexes: file_arceus_api_arceus_proto_depIdxs,
		EnumInfos:         file_arceus_api_arceus_proto_enumTypes,
		MessageInfos:      file_arceus_api_arceus_proto_msgTypes,
	}.Build()
	File_arceus_api_arceus_proto = out.File
	file_arceus_api_arceus_proto_goTypes = nil
	file_arceus_api_arceus_proto_depIdxs = nil
}
