name: Update Submodule in Parent Repo

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Deploy Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no root@46.202.162.37 << 'EOF'
          cd ${{ secrets.VPS_PATH_TO_DOCKER_COMPOSE }}
          docker-compose pull ${{ secrets.VPS_SERVICE_NAME }}
          docker-compose up -d ${{ secrets.VPS_SERVICE_NAME }}
          EOF
